# Generated by Django 5.2.11 on 2026-02-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Album title', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when album was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when album was last updated')),
                ('external_id', models.PositiveIntegerField(blank=True, help_text='External source identifier', null=True, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='albums_albu_title_6c7416_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='album_title_not_empty')],
            },
        ),
    ]
